### ISSUE TITLE
[refactor] Forced withdrawal from a club or self-suspension is prohibited.

### ISSUE THREAD

**Issue by I-migi** [Kernel360/F2_PLAY_BADMINTON_BE#326]
## 어떤 코드를 리팩토링 하는 지 작성 🔍

자기 자신에게 동호회 탈퇴, 동호회워 정지 로직 적용 가능 -> 불가능하게 해야 함

## 주의 사항⚠️
<--해당 기능을 구현 시 주의해야할 사항이 있으면 작성-->

## 소요시간 ⌛️
<--해당 이슈를 해결하는데 예상되는 소요시간을 작성-->

**Comment by km2535** [comment]
프론트와 협의 후 클로즈 할께요

**Comment by km2535** [comment]
프론트에서 제한하기로 하였습니다.
