### ISSUE TITLE
[feat] Can't Force Owner

### ISSUE THREAD

**Issue by I-migi** [Kernel360/F2_PLAY_BADMINTON_BE#353]
## 어떤 기능인지 작성 🔍

동호회 내의 매니저가 동호회 회장을 정지시키거나 강제 탈퇴 시키면 안된다

##  해야 할 일 📝
<-- 어떤 작업이 필요한지 리스트로 작성--> 

## 주의 사항⚠️
<--해당 기능을 구현 시 주의해야할 사항이 있으면 작성-->

## 소요시간 ⌛️
<--해당 이슈를 해결하는데 예상되는 소요시간을 작성-->

**Comment by km2535** [comment]
동호회 회장을 관리하는 부분은 중요하니 로직으로 제한해두겠습니다.
