### ISSUE TITLE
[refactor] 모집 마감 날짜가 지난 경기에 참가 신청 시 에러 메시지 구체적으로 전달하기 (동호회에 가입이 안되어 있어서 / 모집 마감 날짜가 지나서)

### ISSUE THREAD

**Issue by I-migi** [Kernel360/F2_PLAY_BADMINTON_BE#423]
# Project Master
@Yejin0O0

## 어떤 기능인지 작성 🔍
<--기능에 대한 설명-->

##  해야 할 일 📝
<-- 어떤 작업이 필요한지 리스트로 작성--> 

## 주의 사항⚠️
<--해당 기능을 구현 시 주의해야할 사항이 있으면 작성-->

## 소요시간 ⌛️
<--해당 이슈를 해결하는데 예상되는 소요시간을 작성-->

**Comment by km2535** [comment]
이 부분이 403에러가 발생하는 부분이네요
