### ISSUE TITLE
[refactor] 메인화면에서 날짜를 선택하고 새로고침을 했을 때 날짜가 유지되어야 한다

### ISSUE THREAD

**Issue by I-migi** [Kernel360/F2_PLAY_BADMINTON_BE#427]
## 어떤 코드를 리팩토링 하는 지 작성 🔍
<--리팩토링에 대한 설명-->

## 주의 사항⚠️
<--해당 기능을 구현 시 주의해야할 사항이 있으면 작성-->

## 소요시간 ⌛️
<--해당 이슈를 해결하는데 예상되는 소요시간을 작성-->

**Comment by km2535** [comment]
이것도 프론트가 해야하는 일
