### ISSUE TITLE
[refactor] Image optimization for fast load

### ISSUE THREAD

**Issue by km2535** [Kernel360/F2_PLAY_BADMINTON_BE#470]
# Project Master

@Yejin0O0

## 어떤 기능인지 작성 🔍
이미지를 최적화 하는 작업입니다.
모든 이미지 파일을 로드할 때 유리한 webp 와 avif 파일로 컨버팅 합니다. 

## 해야 할 일 📝

- [x] #471 
  - 이미지 컨버팅 
- [x] #472
  - 이벤트 비동기 로직 추가
- [x] #506
  
## 주의 사항⚠️
이미지를 컨버팅하는데 시간이 오래걸립니다. 기존 업로드 시간에서 + 200m/s 
따라서 이미지를 컨버팅할 때 비동기로 처리해야 합니다.❗️

## 소요시간 ⌛️
1 ~ 2일

**Comment by I-migi** [comment]
비동기 로직 추가할 때 배포 환경에서는 현재 이미지 컨버팅이 안되고 오류가 뜨는 상황이라 의존성을 `twelvemonkeys` 로 바꿨고 이 의존성으로 변환하면 이미지가 깨지는 이슈가 발생해요!! 참고해서 로직 구현해주세요!
